#: import utils kivy.utils

<DashboardScreen>
    BoxLayout:
        orientation: "vertical"
        canvas:
            Color:
                rgba: utils.get_color_from_hex("#0d1727")
            Rectangle:
                size: self.size
                pos: self.pos

        ##------------------START OF TOP BAR-------------------##
        BoxLayout:
            orientation: "horizontal"
            size_hint:(1,0.03)
            spacing:"10"

            canvas:
                Color:
                    rgba: utils.get_color_from_hex("#121c2e")
                Rectangle:
                    size: self.size
                    pos: self.pos

            Spacer:
                size_hint:(0.75,1)
            ImageButton:
                id: minimize_btn_id
                source:"icons/Minimize.png"
                size_hint: (None,None)
                height: "18dp"
                width: "18dp"
                pos_hint:{"center_y":0.38}
                on_release:
                    app.minimize()

            ImageButton:
                id: clos_btn_id
                source:"icons/Cross.png"
                size_hint: (None,None)
                height: "18dp"
                width: "18dp"
                pos_hint:{"center_y":0.40}
                on_release:
                    app.close()
            Spacer:
                size_hint:(0.002,1)

        ##------------------END OF TOP BAR-------------------##



        Spacer:
            size_hint : (1,0.04)

        BoxLayout:
            orientation: "horizontal"
            size_hint: (1,0.06)
            Spacer:
                size_hint:(0.37,1)
            Label:
                text:"COVID-19 LIVE BY RAJ"
                font_size: "50sp"
                size_hint: (0.4,1)
                color: utils.get_color_from_hex("#748ca6")
            Spacer:
                size_hint:(0.03,1)
            Image:
                source:"icons/ripple.gif"
                size_hint:(0.1,1)
                anim_delay: 0.08
            Spacer:
                size_hint:(0.3,1)


        BoxLayout:
            orientation: "vertical"
            size_hint:(0.98,0.93)
            pos_hint: {"right": 0.99}



        ##------------------START OF SEARCH BAR-------------------##
            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.1)

                Label:
                    text: "Enter Location "
                    font_size: "20sp"
                    font_name: "SourceSansPro-Regular"
                    size_hint:(0.1,0.4)
                    color: utils.get_color_from_hex("#8F00FF")
                BoxLayout:
                    orientation: "vertical"
                    size_hint: (0.25,0.4)

                    TextInput:
                        id: search_location_id
                        hint_text:""
                        font_size: "15sp"
                        font_name: "roboto_medium"
                        size_hint: (1,0.90)
                        background_color: 0,0,0,0
                        foreground_color: 0.8,0.8,0.8,1
                        multiline: False
                        on_text_validate: app.process_datasearch()


                    BoxLayout:
                        size_hint:(1,0.1)
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex("#2a2f44")
                            Rectangle:
                                size: self.size
                                pos: self.pos
                    Spacer:
                        size_hint:(1,0.05)

                ImageButton:
                    source:"icons/go.png"
                    size_hint: (0.05,0.40)
                    allow_stretch: True
                    keep_aspect: False
                    on_release:
                        app.process_datasearch()
                Spacer:
                    size_hint:(0.01,2)
                Label:
                    id: error_message_id
                    color: utils.get_color_from_hex("#ff0000")
                    font_size:"25px"
                    text:""
                    font_name: "barlow-reg"
                    size_hint:(0.2,0.5)


                Spacer:
                    size_hint:(0.08,1)

                Label:
                    id: date_label_id
                    text:"--"
                    size_hint:(0.1,0.5)
                    font_size: "18sp"
                    font_name: "SourceSansPro-Regular"
                    color:utils.get_color_from_hex("#008000")

                Spacer:
                    size_hint:(0.02,1)

        ##------------------END OF SEARCH BAR-------------------##


            Spacer:
                size_hint:(1,0.05)


        ##------------------START OF CASES BAR-------------------##
            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.425)



        ##------------------START OF CONFIRMED CASES BAR-------------------##
                BoxLayout:
                    orientation:"vertical"
                    size_hint:(0.74,1)
                    spacing: "10"
                    canvas:
                        Color:
                            rgba:utils.get_color_from_hex("#121c2e")
                        Rectangle:
                            size: self.size
                            pos: self.pos



                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1,0.2)
                        Spacer:
                            size_hint:(1,0.1)
                        Label:
                            text: "Confirmed Cases"
                            size_hint:(1,0.9)
                            font_size : "35sp"
                            color: utils.get_color_from_hex("#47546e")
                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1,0.6)

                        Label:
                            id: confirmed_cases_id
                            font_size: "100sp"
                            text: "--"
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#8696ad")

                    BoxLayout:
                        orientation: "horizontal"
                        size_hint: (1,0.2)
                        Spacer:
                            size_hint:(0.20,0.6)
                        Image:
                            source:"icons/up.png"
                            size_hint:(0.05,0.4)
                            pos_hint:{"center_y": 0.5}
                        Label:
                            id: confirmed_cases_delta_id
                            text: "--"
                            font_size: "22sp"
                            font_name: "roboto_medium"
                            size_hint:(0.05,0.6)
                            color: utils.get_color_from_hex("#950d0d")
                            pos_hint:{"center_y": 0.5}

                        Spacer:
                            size_hint:(0.20,0.6)


        ##------------------END OF CONFIRMED CASES BAR-------------------##

                Spacer:
                    size_hint:(0.01,1)

                BoxLayout:
                    orientation:"vertical"
                    size_hint:(0.74,1)
                    spacing: "10"

                    canvas:
                        Color:
                            rgba:utils.get_color_from_hex("#0d1727")
                        Rectangle:
                            size: self.size
                            pos: self.pos


        ##------------------START OF CONFIRMED DEATHS BAR-------------------##
                    BoxLayout:
                        orientation:"vertical"
                        size_hint:(1,0.5)
                        spacing: "1"
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex("#121c2e")
                            Rectangle:
                                size: self.size
                                pos : self.pos

                        Spacer:
                            size_hint:(1,0.1)
                        Label:
                            text: "Confirmed Deaths"
                            font_size: "22sp"
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint:(1,0.1)

                        Label:
                            id: confirmed_deaths_id
                            font_size: "60sp"
                            text: "--"
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint:(1,0.5)

                        BoxLayout:
                            orientation: "horizontal"
                            size_hint: (1,0.2)

                            Spacer:
                                size_hint:(0.38,0.6)

                            Image:
                                source: "icons/up.png"
                                size_hint: (0.05,0.7)
                                pos_hint: {"center_y":0.5}
                            Label:
                                id: confirmed_deaths_delta_id
                                text: "--"
                                font_size: "22sp"
                                size_hint: (0.05,0.6)
                                font_name: "roboto_medium"
                                color: utils.get_color_from_hex("#950d0d")
                                pos_hint:{"center_y":0.5}

        ##------------------END OF CONFIRMED DEATHS BAR-------------------##

                            Spacer:
                                size_hint:(0.38,0.6)


        ##------------------START OF ACTIVE CASES BAR-------------------##
                    BoxLayout:
                        orientation:"vertical"
                        size_hint:(1,0.5)
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex("#121c2e")
                            Rectangle:
                                size: self.size
                                pos: self.pos


                        Spacer:
                            size_hint:(1,0.1)

                        Label:
                            text:"Active Cases"
                            font_size: "22sp"
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint:(1,0.1)

                        Label:
                            id: active_cases_id
                            font_name: "roboto_medium"
                            text:"--"
                            font_size: "55sp"
                            color:utils.get_color_from_hex("#47546e")
                            size_hint:(1,0.5)

                        BoxLayout:
                            orientation: "horizontal"
                            size_hint:(1,0.2)

                            Spacer:
                                size_hint:(0.20,0.6)
                            Image:
                                source:"icons/down.png"
                                size_hint:(0.05,0.5)
                                pos_hint: {"center_y": 0.5}
                            Spacer:
                                size_hint:(0.001,0.6)
                            Label:
                                id: critical_cases_id
                                text: "--"
                                font_size: "15sp"
                                font_name: "roboto_medium"
                                color: utils.get_color_from_hex("#FFA500")
                                size_hint:(0.08,0.8)
                                pos_hint:{"center_y": 0.5}
                            Spacer:
                                size_hint:(0.20,0.6)
                        Spacer:
                            size_hint:(1,0.1)

        ##------------------END OF ACTIVE CASES BAR-------------------##

        ##----------------------END OF CASES BAR----------------------##
            Spacer:
                size_hint:(1,0.025)

        ##----------------------START OF RECOVERED CASES BAR----------------------##

            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.3)

                BoxLayout:
                    orientation: "horizontal"
                    size_hint:(0.74,1)
                    id: cases_plot_id
                    spacing: "10"

                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex("#121c2e")
                        Rectangle:
                            size: self.size
                            pos: self.pos


                Spacer:
                    size_hint:(0.01,1)

                BoxLayout:
                    orientation: "vertical"
                    size_hint:(0.25,1)
                    spacing: "10"

                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex("#121c2e")
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    Spacer:
                        size_hint:(1,0.2)
                    Label:
                        text: "Recovered"
                        font_size: "24sp"
                        font_name: "roboto_medium"
                        color: utils.get_color_from_hex("#47546e")
                        size_hint: (1,0.5)

                    Label:
                        id: recovered_cases_id
                        text:"--"
                        font_size: "55sp"
                        font_name: "roboto_medium"
                        color: utils.get_color_from_hex("#47546e")
                        size_hint:(1,1)
                    BoxLayout:
                        orientation: "horizontal"
                        size_hint: (1,0.1)

                        Spacer:
                            size_hint:(0.40,0.6)
                        Image:
                            source:"icons/upgreen.png"
                            size_hint:(0.05,2)
                            pos_hint: {"center_y": 0.5}
                        Spacer:
                            size_hint:(0.01,0.2)
                        Label:
                            id: recovery_rate_id
                            text:"--"
                            font_size: "15sp"
                            size_hint: (0.4,0.6)
                            font_name: "roboto_medium"
                            color: utils.get_color_from_hex("#006994")
                            pos_hint: {"center_y":0.5}
                        Spacer:
                            size_hint:(0.25,0.1)
                    Spacer:
                        size_hint:(1,0.1)





            Spacer:
                size_hint:(1,0.03)